### ISSUE TITLE
ubuntu 22.04 "no longer signed"

### ISSUE THREAD

**Issue by foucdeg** [microsoft/linux-package-repositories#130] opened 2024-04-24 08:57 UTC
**Describe the issue**

Getting this error in a Github Actions job:

```
apt-get update
  Get:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
  Err:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
    Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)

E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
  E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.

```

**When did the issue occur?**

Around 8:40 UTC today (April 24th 2024)

**If applicable, what package did you attempt to install, and from which repo?**

ubuntu/22.04/prod jammy InRelease

**Comment by KerstinKeller** [comment] 2024-04-24 09:01
Encountering the exact same issue, see build log:
https://github.com/eclipse-ecal/ecal/actions/runs/8813839529/job/24192444569?pr=1562

**Comment by PietroPasotti** [comment] 2024-04-24 09:05
same-same on all our repos e.g. https://github.com/canonical/traefik-k8s-operator/actions/runs/8813690572/job/24192769293

**Comment by jserpapinto** [comment] 2024-04-24 09:36
Same on all our repos:

```
deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ jammy main
/usr/bin/sudo apt update

WARNING: apt does not have a stable CLI interface. Use with caution in scripts.

Get:1 file:/etc/apt/apt-mirrors.txt Mirrorlist [142 B]
Get:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Err:6 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:2 http://azure.archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://azure.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://azure.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 http://azure.archive.ubuntu.com/ubuntu jammy-security InRelease
Hit:7 https://pkg.cloudflareclient.com/ jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/ubuntu-toolchain-r/test/ubuntu jammy InRelease
Reading package lists...
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
```

**Comment by rami3l** [comment] 2024-04-24 09:40
This is preventing a new Rustup release from happening: https://github.com/rust-lang/rustup/actions/runs/8813751430/job/24192170374

**Comment by svorcan-rho** [comment] 2024-04-24 09:43
Encountering same issue starting today.

**Comment by siggerzz** [comment] 2024-04-24 09:51
I _think_ this might be fixed now. My local machine now fetches this file successfully 👍🏼

**Comment by ThibaultCoudertSephora** [comment] 2024-04-24 09:52
Same issue since this morning 8:40AM.

**Comment by osesantos** [comment] 2024-04-24 10:16
Same is happening on all our repos
```
. prepare: . prepare:playwright: Get:20 http://azure.archive.ubuntu.com/ubuntu jammy-security/restricted Translation-en [299 kB]
. prepare: . prepare:playwright: Get:21 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [848 kB]
. prepare: . prepare:playwright: Get:22 http://azure.archive.ubuntu.com/ubuntu jammy-security/universe Translation-en [163 kB]
. prepare: . prepare:playwright: Reading package lists...
. prepare: . prepare:playwright: E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
. prepare: . prepare:playwright: E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
. prepare: . prepare:playwright: Failed to install browsers
. prepare: . prepare:playwright: Error: Installation process exited with code: 100
. prepare: . prepare:playwright: Failed
. prepare:  ELIFECYCLE  Command failed with exit code 1.
. prepare: Failed
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by windnfc** [comment] 2024-04-24 10:23
Same here. Yesterday it was still working fine.

**Comment by wjz304** [comment] 2024-04-24 10:24
+1

**Comment by JJD1990** [comment] 2024-04-24 10:25
+1

**Comment by stefanahman** [comment] 2024-04-24 10:31
A workaround for the ones in panic:
```
sudo apt-get update || true
```

**Comment by edlerd** [comment] 2024-04-24 10:33
+1 since about 1 hour.

**Comment by jolelievre** [comment] 2024-04-24 10:56
Same issue on all our CI for the PrestaShop project https://github.com/PrestaShop/PrestaShop/actions/runs/8814445565/job/24196124300?pr=35998

**Comment by AaqibFarooq1** [comment] 2024-04-24 11:01
+1

**Comment by eggplants** [comment] 2024-04-24 11:03
`playwright install --with-deps chromium` has failed in `apt-get update` step on GitHub Actions due to this issue.

**Comment by MatteoJoliveau** [comment] 2024-04-24 11:04
May I kindly request that people stop commenting with `+1` or reports of their repository being affected?
It adds a lot of noise to this issue, I subscribed to be notified when the issue is resolved or for possible workarounds, having my inbox filled with emails that do not contribute anything to the topic is not great :)

**Comment by lukasklein** [comment] 2024-04-24 11:16
I miss the days where someone with simple FTP access to packages.microsoft.com could fix this real quick.

**Comment by hasnatdevops** [comment] 2024-04-24 11:21
Please use below solution instead of **ubuntu-latest** in the github actions CI/CD file for quick fix
 
runs-on: ubuntu-20.04

**Comment by mcw92** [comment] 2024-04-24 11:44
Same for our repo in the [testing workflow](https://github.com/Helmholtz-AI-Energy/propulate/actions/runs/8814111676/job/24193271833?pr=116) when using [this action](https://github.com/mpi4py/setup-mpi?tab=readme-ov-file) for setting up MPI.

**Comment by DeanMarques** [comment] 2024-04-24 12:00
Same here :(  surely the repo is the issue.. if I web browse and click inRelease nothing occurs just a blank page where as for focal it downloads the Release.gpg file

![image](https://github.com/microsoft/linux-package-repositories/assets/27240502/905f6312-12be-47ad-8ba0-0ef77dc7f9f2)

**Comment by MichaIng** [comment] 2024-04-24 12:05
> if I web browse and click inRelease nothing occurs just a blank page where as for focal it downloads the Release.gpg file

In fact it throws a 403 (forbidden), when trying to access. The `Release` and `Release.gpg` work, but APT seems to not fall back to trying them automatically, if `InRelease` exists (403 vs 404?).

**Comment by DeanMarques** [comment] 2024-04-24 12:07
I can confirm with a fresh install of ubuntu and running the for ODBC driver 17 install following the instructions here:

**https://learn.microsoft.com/en-us/sql/connect/odbc/linux-mac/installing-the-microsoft-odbc-driver-for-sql-server?view=sql-server-ver16&tabs=alpine18-install%2Cubuntu17-install%2Cubuntu16-install%2Credhat7-13-install%2Crhel7-offline#1**7

Same issue occurs whening trying to run apt update: 
sudo apt update
Get:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Err:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
Hit:2 http://za.archive.ubuntu.com/ubuntu jammy InRelease
Hit:3 http://za.archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:4 http://za.archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:5 http://security.ubuntu.com/ubuntu jammy-security InRelease
Reading package lists... Done
E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
root@test:~# cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by LukeDearden** [comment] 2024-04-24 12:11
Same issue here attempting to install pwsh 

 ```
 wget -q https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb
  dpkg -i packages-microsoft-prod.deb
  apt-get update
```

results in  

```
Get:5 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
Err:5 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
```

**Comment by jypuigbo** [comment] 2024-04-24 12:12
same issue here

**Comment by rami3l** [comment] 2024-04-24 12:17
I think the conversation is already too heated at this point.

For those who have also encountered this issue, please include the link to this issue in your own repo rather than comment directly below. This way the subscribers will receive fewer notifications.
For those who are subscribed to this issue, you may try to adjust the notification level in `Notifications-Customize`.

<img width="863" alt="image" src="https://github.com/microsoft/linux-package-repositories/assets/33851577/f52b6ecd-473b-4fae-97e1-d13b2482d63c">

**Comment by SqlOwl** [comment] 2024-04-24 12:20
I am facing the same issue when installing msodbcsql18 on Databricks Ubuntu 22.04 node

**Comment by jypuigbo** [comment] 2024-04-24 12:22
In case it helps, I'm having the same issue running this basic dockerfile: 
```
FROM ubuntu-20.04
FROM python:3.12

USER root

RUN apt-get update 
# adding custom MS repository
RUN wget https://packages.microsoft.com/config/ubuntu/22.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb

RUN apt-get update

RUN ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev
```

Notice that removing `microsoft-prod.list` (as suggested somewhere above) will not solve the problem, it just means you no longer needed to have this file and didn't clean, or it will generate issues for you later.

**Comment by florisKlinkert** [comment] 2024-04-24 12:36
Same issue here.

Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)

jammy InRelease' is no longer signed.

**Comment by screig** [comment] 2024-04-24 13:06
Captain Chaos approves of the state of affairs with Microsoft APT repos

**Closed** 2024-04-24 13:08 UTC
Labels: bug

**Comment by JJD1990** [comment] 2024-04-24 13:32
Thanks for your work on sorting this, all seems good for us.

**Comment by ben-matthews6-NHSD** [comment] 2024-04-24 15:06
> Thanks for your work on sorting this, all seems good for us.

Ditto for us - thank you 👍

**Comment by Janebeem** [comment] 2024-05-08 18:51
> Encountering the exact same issue, see build log: https://github.com/eclipse-ecal/ecal/actions/runs/8813839529/job/24192444569?pr=1562

[](url)

**Comment by oriolpiera** [comment] 2024-05-09 04:49
> > Encountering the exact same issue, see build log: https://github.com/eclipse-ecal/ecal/actions/runs/8813839529/job/24192444569?pr=1562

@Janebeem re-run jobs and it should work

**Comment by Janebeem** [comment] 2024-05-12 21:36
> **Describe the issue**
> 
> Getting this error in a Github Actions job:
> 
> ```
> apt-get update
>   Get:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
>   Err:1 https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease
>     Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
> 
> E: Failed to fetch https://packages.microsoft.com/ubuntu/22.04/prod/dists/jammy/InRelease  Clearsigned file isn't valid, got 'NOSPLIT' (does the network require authentication?)
>   E: The repository 'https://packages.microsoft.com/ubuntu/22.04/prod jammy InRelease' is no longer signed.
> ```
> 
> **When did the issue occur?**
> 
> Around 8:40 UTC today (April 24th 2024)
> 
> **If applicable, what package did you attempt to install, and from which repo?**
> 
> ubuntu/22.04/prod jammy InRelease

**Comment by mbearup** [comment] 2024-05-14 11:14
@Janebeem this issue was resolved on 24Apr; any jobs run since then should be successful. Have you tried running this since 24Apr?

**Comment by Titas-OpenTrack** [comment] 2024-05-24 08:55
@mbearup It has been working fine for a while, but the error has returned in the past few days:

> W: Failed to fetch http://deb.debian.org/debian-security/dists/bullseye-security/InRelease  Error reading from server - read (104: Connection reset by peer) [IP: 151.101.50.xxx xx]
> --
> 75 | E: Failed to fetch http://deb.debian.org/debian/dists/bullseye/main/binary-amd64/Packages  Connection timed out [IP: 151.101.50.xxx xx]

**Comment by mbearup** [comment] 2024-05-28 13:46
@Titas-OpenTrack the error message is from debian.org. This forum is only for issues on packages.microsoft.com.
