### ISSUE TITLE
Failed to fetch https://pmc-geofence.trafficmanager.net/ - TLS fatal alert

### ISSUE THREAD

**Issue by abendezub** [microsoft/linux-package-repositories#171] opened 2024-09-11 20:23 UTC
**Describe the issue**
 We are trying to install mssql-tools from different locations. Install in an docker build fails.

**When did the issue occur?**
Using AzureDevops Pipeline for Docker container creation.

**If applicable, what package did you attempt to install, and from which repo?**

mssql-tools

https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64

**Steps to Reproduce**
RUN apt-get install -y curl
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/ubuntu/20.04/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update
RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated msodbcsql17
RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated mssql-tools

**Actual Result**
#15 1.400 The following NEW packages will be installed:
#15 1.400   mssql-tools
#15 1.656 0 upgraded, 1 newly installed, 0 to remove and 28 not upgraded.
#15 1.656 Need to get 211 kB of archives.
#15 1.656 After this operation, 0 B of additional disk space will be used.
#15 1.656 Err:1 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 mssql-tools amd64 17.10.1.1-1
#15 1.656   Could not handshake: A TLS fatal alert has been received. [IP: 4.155.111.140 443]
#15 1.663 E: Failed to fetch https://pmc-geofence.trafficmanager.net/ubuntu/20.04/prod/pool/main/m/mssql-tools/mssql-tools_17.10.1.1-1_amd64.deb?geofence=true  Could not handshake: A TLS fatal alert has been received. [IP: 4.155.111.140 443]
#15 1.663 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
#15 ERROR: process "/bin/sh -c ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated mssql-tools" did not complete successfully: exit code: 100
------
 > [11/23] RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated mssql-tools:
1.263 Reading state information...
1.400 The following NEW packages will be installed:
1.400   mssql-tools
1.656 0 upgraded, 1 newly installed, 0 to remove and 28 not upgraded.
1.656 Need to get 211 kB of archives.
1.656 After this operation, 0 B of additional disk space will be used.
1.656 Err:1 https://packages.microsoft.com/ubuntu/20.04/prod focal/main amd64 mssql-tools amd64 17.10.1.1-1
1.656   Could not handshake: A TLS fatal alert has been received. [IP: 4.155.111.140 443]
1.663 E: Failed to fetch https://pmc-geofence.trafficmanager.net/ubuntu/20.04/prod/pool/main/m/mssql-tools/mssql-tools_17.10.1.1-1_amd64.deb?geofence=true  Could not handshake: A TLS fatal alert has been received. [IP: 4.155.111.140 443]
1.663 E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
------
Dockerfile:17
--------------------
  15 |     RUN apt-get update
  16 |     RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated msodbcsql17
  17 | >>> RUN ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated mssql-tools
  18 |     RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
  19 |     RUN echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
--------------------
ERROR: failed to solve: process "/bin/sh -c ACCEPT_EULA=Y apt-get install -y --allow-unauthenticated mssql-tools" did not complete successfully: exit code: 100

**Expected Result**
Successfull installation of the package on the container build.

**Comment by daviddavis** [comment] 2024-09-11 20:31
Duplicate of https://github.com/microsoft/linux-package-repositories/issues/170

**Closed by daviddavis** 2024-09-11 20:31 UTC
Labels: bug
