### ISSUE TITLE
SQL Server 2019 install fails -- the repository is not signed

### ISSUE THREAD

**Issue by dustin-rcg** [microsoft/linux-package-repositories#45] opened 2023-02-28 21:50 UTC
**Describe the issue**
Trying to install SQL Server on Ubuntu 20.04 as described [here](https://learn.microsoft.com/en-us/sql/linux/sql-server-linux-change-repo?view=sql-server-ver16&pivots=ld2-ubuntu) now fails with the error `The repository 'https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal Release' is not signed.`

**When did the issue occur?**
First occurred at 2023-02-28 20:56:32 UTC.

**If applicable, what package did you attempt to install, and from which repo?**

https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019

**Steps to Reproduce**

```
RUN export DEBIAN_FRONTEND=noninteractive \
  && apt-get update \
  && apt-get install -yq curl apt-transport-https ca-certificates gnupg wget \
  # Get official Microsoft repository configuration
  && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
  && curl https://packages.microsoft.com/config/ubuntu/20.04/mssql-server-2019.list | tee /etc/apt/sources.list.d/mssql-server.list \
  && apt-get update \
  # Install SQL Server from apt
  && apt-get install -y mssql-server \
  # Install optional packages
  && apt-get install -y mssql-server-fts \
  # Cleanup the Dockerfile
  && apt-get clean \
  && rm -rf /var/lib/apt/lists 
```

**Actual Result**

```
2023-02-28 20:56:28. deb [arch=amd64,armhf,arm64] https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal main
2023-02-28 20:56:28. Hit:1 http://security.ubuntu.com/ubuntu focal-security InRelease
2023-02-28 20:56:28. Ign:2 https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal InRelease
2023-02-28 20:56:28. Get:3 https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal Release [2532 B]
2023-02-28 20:56:28. Ign:4 https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal Release.gpg
2023-02-28 20:56:29. Hit:5 http://archive.ubuntu.com/ubuntu focal InRelease
2023-02-28 20:56:29. Hit:6 http://archive.ubuntu.com/ubuntu focal-updates InRelease
2023-02-28 20:56:29. Hit:7 http://archive.ubuntu.com/ubuntu focal-backports InRelease
2023-02-28 20:56:29. Reading package lists...
2023-02-28 20:56:32. 
2023-02-28 20:56:32. E: The repository 'https://packages.microsoft.com/ubuntu/20.04/mssql-server-2019 focal Release' is not signed.
```

**Expected Result**

The installation completes without error.

**Screenshots**

**Additional context**

This build script was working fine earlier. The script has not changed.  This is failing both locally and in our Codeship CI.

**Comment by daviddavis** [comment] 2023-02-28 21:55
Duplicate of https://github.com/microsoft/linux-package-repositories/issues/44.

**Closed by daviddavis** 2023-02-28 21:55 UTC
Labels: bug
